### ISSUE TITLE
Let's merge efforts

### ISSUE THREAD

**Issue by atgreen** [hjudt/s2i-lisp#1]
Hi hjudt,

  I'm back to some lisp hacking on OpenShift, and stumbled across your many great improvements to s2i-lisp.  Are you open to collaborating on a single repo?  Something like a 'containerlisp' org in github and dockerhub where we maintain a single source for people to find the latest and greatest version of s2i-lisp?

**Comment by hjudt** [comment]
That would be fun and also more people maintaining it would help keeping it up-to-date. At the moment, I guess I am probably the only user of my repo, and I am maintaining it regularly and improving it because I need the features for some OpenShift projects. It is, nevertheless, listed in [awesome-cl](https://github.com/CodyReichert/awesome-cl).

**Comment by atgreen** [comment]
Hey... also please confirm that I've set things up properly and you can commit to the container-lisp repo.

**Comment by hjudt** [comment]
I can clone and pull from the repository but not push to it (permission denied).

**Comment by atgreen** [comment]
Ok, I just changed you from 'member' to 'owner'.  Let me know if that works.

AG

**Comment by hjudt** [comment]
Thanks, it works now.

I've pushed two changes by now.

BTW: You can do "git pull --rebase" before pushing to avoid unnecessary "merge" commits.

**Comment by hjudt** [comment]
Is there some other way to contact you or talk to you? Freenode IRC perhaps? I do linger there in the #lisp channel most times...

**Comment by atgreen** [comment]
I sit on #lisp when I can.  I'm 'atgreen'

**Comment by hjudt** [comment]
[Pull request](https://github.com/CodyReichert/awesome-cl/pull/232) to update the reference on awesome-cl created. I am closing this issue now.
